services:
  convert-code-server:
    build: 
      context: .
      dockerfile: convert_code.Dockerfile
    container_name: convert-code
    ports:
      - "3334:3334"
    expose:
      - "3334"
  redis:
    image: redis:7.2-rc2-alpine
    ports:
      - "6380:6380"
  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
  #   env_file:
  #     - .env
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CODE_CONVERT_HOST=convert-code-server
      - CODE_CONVERT_PORT=3334
    depends_on:
      - redis
      - postgres
      - convert-code-server
    # command: ["ls"]
 