services:
  convert-code-server:
    build: 
      context: .
      dockerfile: convert_code.Dockerfile
    container_name: convert-code
    ports:
      - "3333:3333"
    expose:
      - "3333"
  redis:
    image: redis:7.2-rc2-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
  #   env_file:
  #     - .env
  #   restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CODE_CONVERT_HOST=convert-code-server
      - CODE_CONVERT_PORT=3334
    depends_on:
      - redis
      - convert-code-server
 