# Generated by Django 4.1.5 on 2023-01-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Move name')),
                ('cat', models.CharField(choices=[('U', 'UI'), ('O', 'Official'), ('C', 'Custom')], max_length=10)),
                ('color', models.CharField(max_length=20, verbose_name='rgb color string')),
                ('implementation', models.TextField(blank=True)),
                ('overview', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('symbol', models.CharField(blank=True, max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='PieceMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_row', models.SmallIntegerField()),
                ('relative_col', models.SmallIntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.move')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.piece')),
            ],
        ),
        migrations.CreateModel(
            name='PieceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boardsetup')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.piece')),
            ],
        ),
        migrations.AddIndex(
            model_name='piecemove',
            index=models.Index(fields=['piece'], name='api_piecemo_piece_i_e3254f_idx'),
        ),
        migrations.AddIndex(
            model_name='piecelocation',
            index=models.Index(fields=['board'], name='api_piecelo_board_i_6526c2_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['name', 'author'], name='api_move_name_a970a7_idx'),
        ),
    ]
