# Generated by Django 4.1.5 on 2023-01-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Move name')),
                ('cat', models.CharField(choices=[('U', 'UI'), ('O', 'Official'), ('C', 'Custom')], max_length=10)),
                ('color', models.CharField(max_length=20, verbose_name='rgb color string')),
                ('border_color', models.CharField(blank=True, max_length=20, verbose_name='rgb boarder color string')),
                ('implementation', models.TextField(blank=True)),
                ('overview', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('symbol', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_row', models.SmallIntegerField()),
                ('relative_col', models.SmallIntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chessplexApp.move')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.piece')),
            ],
        ),
        migrations.CreateModel(
            name='PieceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.user')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.boardsetup')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chessplexApp.piece')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.user'),
        ),
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chessplexApp.image'),
        ),
        migrations.AddField(
            model_name='move',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.user'),
        ),
        migrations.AddField(
            model_name='boardsetup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessplexApp.user'),
        ),
        migrations.AddIndex(
            model_name='piecemove',
            index=models.Index(fields=['piece'], name='chessplexAp_piece_i_718408_idx'),
        ),
        migrations.AddIndex(
            model_name='piecelocation',
            index=models.Index(fields=['board'], name='chessplexAp_board_i_611809_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['name', 'author'], name='chessplexAp_name_f23687_idx'),
        ),
    ]
