# Generated by Django 4.1.5 on 2023-01-17 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecelocation',
            name='col',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='piecelocation',
            name='row',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='piecemove',
            name='relative_col',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-7), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='piecemove',
            name='relative_row',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-7), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
