# Generated by Django 4.1.5 on 2023-01-25 00:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_piecelocation_col_alter_piecelocation_row_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pieces/')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='cat',
            field=models.CharField(choices=[('official', 'Official'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='move',
            name='cat',
            field=models.CharField(choices=[('UI', 'Ui'), ('official', 'Official'), ('custom', 'Custom')], max_length=10),
        ),
        migrations.AlterField(
            model_name='move',
            name='color',
            field=models.CharField(max_length=20, validators=[api.models.validate_color], verbose_name='rgb color string'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.imagemodel'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
