# Generated by Django 4.1.5 on 2023-02-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagemodel_piece_cat_alter_move_cat_alter_move_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(upload_to='pieces/'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
