# Generated by Django 4.1.5 on 2023-03-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_move_api_move_name_a970a7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecelocation',
            name='author',
        ),
    ]
