# Generated by Django 4.1.5 on 2023-04-12 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_piecelocation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsetup',
            name='cat',
            field=models.CharField(choices=[('official', 'Official'), ('custom', 'Custom'), ('game', 'Game In Progress')], max_length=10),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_to_move', models.BooleanField(default=True)),
                ('black_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='black_user', to=settings.AUTH_USER_MODEL)),
                ('board_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boardsetup')),
                ('white_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='white_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
