# Generated by Django 4.2 on 2023-04-17 01:29

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_boardsetup_cat_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsetup',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[api.models.validate_simple_name]),
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boardsetup')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
