# Generated by Django 4.2 on 2023-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_boardsetup_name_gamerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='black_user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='board_setup',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_user',
        ),
        migrations.RemoveIndex(
            model_name='piecelocation',
            name='api_piecelo_boardSe_9efb58_idx',
        ),
        migrations.RenameField(
            model_name='piecelocation',
            old_name='boardSetup',
            new_name='board_setup',
        ),
        migrations.AddIndex(
            model_name='piecelocation',
            index=models.Index(fields=['board_setup'], name='api_piecelo_board_s_22f61b_idx'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
