# Generated by Django 4.2 on 2023-06-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_gamerequest_requesting_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsetup',
            name='wincon_black',
            field=models.CharField(choices=[('anyR', 'Kill Any Royal'), ('allR', 'Kill All Royals'), ('all', 'Kill All')], default='all', max_length=4),
        ),
        migrations.AddField(
            model_name='boardsetup',
            name='wincon_white',
            field=models.CharField(choices=[('anyR', 'Kill Any Royal'), ('allR', 'Kill All Royals'), ('all', 'Kill All')], default='all', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('W', 'White Win'), ('B', 'Black Win'), ('D', 'Draw'), ('P', 'In Progress')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='piecelocation',
            name='is_royal',
            field=models.BooleanField(default=False),
        ),
    ]
