# Generated by Django 4.2 on 2023-06-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_boardsetup_wincon_black_boardsetup_wincon_white_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='name',
        ),
    ]
