# Generated by Django 4.2.2 on 2023-06-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_move_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='cat',
            field=models.CharField(choices=[('UI', 'Ui'), ('official', 'Official'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
