# Generated by Django 4.2.2 on 2023-06-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_move_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='setup_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.boardsetup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardsetup',
            name='cat',
            field=models.CharField(choices=[('official', 'Official'), ('custom', 'Custom')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('W', 'White Win'), ('Y', 'White Win Resign'), ('B', 'Black Win'), ('C', 'Black Win Resign'), ('D', 'Draw'), ('E', 'Draw Agreed'), ('P', 'In Progress')], default='P', max_length=1),
        ),
    ]
