# Generated by Django 4.2.2 on 2023-06-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_setup_name_game_setup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image_black',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image_white',
            field=models.BinaryField(blank=True),
        ),
    ]
